### ISSUE TITLE
Error reading csv file

### ISSUE THREAD

**Issue by Pindol83** [dickwolff/Trading-212-to-Ghostfolio#1]
I'm trying the tool to convert the CSV file to JSON so that it can be read by Ghostfolio, but it's giving me this error. What is causing it and how can I solve it?

[nodemon] starting `ts-node ./src/index.ts`
Read CSV file /Users/xxxx/xxxx/trading212_2022.csv. Start processing..
/Users/xxxx/Trading-212-to-Ghostfolio-main/src/index.ts:28
const csvFile = fs.readFileSync(inputFile, "utf-8");
                                                         ^
TypeError: Cannot read properties of undefined (reading 'length')
    at /Users/xxxx/Trading-212-to-Ghostfolio-main/src/index.ts:119:28
    at Generator.next (<anonymous>)
    at fulfilled (/Users/xxxx/Trading-212-to-Ghostfolio-main/src/index.ts:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by dickwolff** [comment]
Hi,

I'm pretty sure this has to do with a column mismatch. 

Can you please send me the header line of your CSV export and also tell me which kind of data is in the export? Like buy/sell/dividend etc. This helps me to analyse where the exact error is. Thanks!

**Comment by Pindol83** [comment]
Hi,

the header line of CSV is:
Action,Time,ISIN,Ticker,Name,No. of shares,Price / share,Currency (Price / share),Exchange rate,Result,Currency (Result),Total,Currency (Total),Withholding tax,Currency (Withholding tax),Notes,ID,Currency conversion fee,Currency (Currency conversion fee),French transaction tax,Currency (French transaction tax)

and the CSV includes all type of data (orders, dividends, transactions, interest)

thanks for your help

**Comment by Pindol83** [comment]
did you have time to work on it?

thanks for your patience

**Comment by dickwolff** [comment]
Sorry, I haven't had the time to make a fix. I do however have an idea to make it more fault proof for the future. I'll try to work on that this week.

**Comment by Pindol83** [comment]
Any news?

thanks for your patience

**Comment by dickwolff** [comment]
Sorry for the wait, I have been busy recently so haven't had the time to continue. I have some code but don't have possibility to verify it now. I have some time tomorrow evening, so I'll try to verify then if it works and will post an update here.

**Comment by dickwolff** [comment]
I have pushed my changes on [this](https://github.com/dickwolff/Trading-212-to-Ghostfolio/tree/feature/Read-Columns-Dynamic) branch. Could you check this out and try if it works for you now?

This is a more generalized solution which just parses all columns, so there is no more need for adding or removing columns whenever something changes in the export format.

**Comment by Pindol83** [comment]
It seems to be working, but after a while, it gives me a syntax error related to a symbol. How do I find the row in the CSV where it's getting stuck?

 ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 10% | ETA: 14468s | 127/1159/mypath/Trading-212-to-Ghostfolio-main_2/src/index.ts:28
    if (!colsInFile[idx]) {
                                                         ^
TypeError: Cannot read properties of undefined (reading 'symbol')
    at /mypath/Trading-212-to-Ghostfolio-main_2/src/index.ts:141:38
    at Generator.next (<anonymous>)
    at fulfilled (/mypath/Trading-212-to-Ghostfolio-main_2/src/index.ts:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by dickwolff** [comment]
This seems to be in regard to Ghostfolio not returning a ticker symbol (like AAPL). Which record is on position 127 in your Trading 212 export?

**Comment by Pindol83** [comment]
The line in question is this one:
Market buy,2023-03-01 14:35:15,CA0679011084,GOLD,"Barrick Gold",0.1785470000,16.38,USD,1.06739,"EUR",2.74,"EUR",,,,,,EOF2292308114,,,,

But I don't seem to notice anything unusual, perhaps Ghostfolio is confusing Barrik's ticker with real gold?
With another CSV, it gets stuck on the ticker for MARA.

**Comment by dickwolff** [comment]
The ISIN shows a result in Yahoo Finance (the underlying source for Ghostfolio), so this is a weird case.

It would help me if you could provide a file that won't process. That way I can check what goes wrong myself and expedite a fix.

**Comment by Pindol83** [comment]
Certainly, where can I send you the file? Can I have your email or your Telegram account?

Thanks

**Comment by dickwolff** [comment]
My telegram handle is @dickwolff.
